repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.14
  hooks:
    # ruff linter - on par with `uvx ruff check`
    - id: ruff-check
    # ruff formatter - on par with `uvx ruff format`
    - id: ruff-format
